spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mariadb://144.122.71.113:8083/group12
    username: group12
    password: claZg6xkoNaZbvJ
    driver-class-name=org: mariadb.jdbc.Driver
  jpa:
    show-sql: true


  mail:
    host: smtp.example.com #create a new email address and configure
    port: 587
    username: username@example.com
    password: password
    properties:
      smtp.auth: true
      starttls.enable: true


server:
  servlet:
    session:
      cookie:
        max-age: 30m
