spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mariadb://144.122.71.113:8083/group12
    username: group12
    password: claZg6xkoNaZbvJ
    driver-class-name=org: mariadb.jdbc.Driver
  jpa:
    show-sql: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher


  mail:
    host: smtp.gmail.com #create a new email address and configure
    port: 587
    username: 453.group12@gmail.com
    password: pgitfytlsbjghbmk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    session:
      cookie:
        max-age: 30m

springfox:
  documentation:
    swagger-ui:
      enabled: true
