spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/group12
    username: holynekk
    password: ()mert2345
    driver-class-name=org: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

server:
  servlet:
    session:
      cookie:
        max-age: 30m

springfox:
  documentation:
    swagger-ui:
      enabled: true
    enables: true
