package com.group12.model.chat;

public enum MessageType {
  CONNECT,
  CONNECT_OK,
  CONNECT_FAILED,
  USER_JOINED,
  USER_LIST,
  READY,
  DISCONNECT,
  KICK,
  BAN,
  LOBBY_CHAT,
  IN_GAME_CHAT,
  START_GAME,
  SHOW_ROADS_AT_SETUP,
  SHOW_SETTLEMENTS_AT_SETUP,
  THROW_DICE,
  SKIP_TURN,
  SKIP_SETUP_TURN,
  BUILD_ROAD,
  BUILD_SETTLEMENT,
  UPGRADE_SETTLEMENT
}
